
import type { Metadata } from "next";
import { auth } from "@/services/auth";
import { redirect } from "next/navigation";

import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { AuthProvider } from "@/providers/AuthProvider";
import { QueryProvider } from "@/providers/QueryProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";
import DashboardLayout from "@/app/_components/layout";



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
const locales = ["en", "pt-BR"];

export default async function RootLayout({
    children, params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const session = await auth()
    if (!session?.user) {
        redirect('/auth/signin')
    }
    const isValidLocale = locales.some((cur) => cur === locale);
    if (!isValidLocale) notFound();
    //@ts-ignore
    const messages = await getMessages(locale);
    return (
        <AuthProvider>
            <DashboardLayout>
                {children}
            </DashboardLayout>
        </AuthProvider>
    );
}
